### PR TITLE
Compatibility to TYPO3 8.7 LTS

### LINKED ISSUE #25: TYPO3 v8 LTS (8.7) compatibility
Would be great if you could make it compatible with the latest LTS release.

### PR DESCRIPTION
**Pull request by kartolo**
resolves #25

### CODE REVIEW

**Comment by angeloprevitali** [comment]
+1

**Comment by angeloprevitali** [comment]
I found a little "bug" (if this is really a bug?) on the #25: If you want to add XLF files into the template the XLF gets not rendered in the FE. Can you fix this? Possible? On the EXT:direct_mail it works.

**Comment by kartolo** [comment]
please post your TypoScript. Thanks

**Comment by angeloprevitali** [comment]
In the template i would like to add something like this:



<b><label for="fe_ttaddress_name_input">**<f:translate key="LLL:fileadmin/templates/direct_mail_subscription/Language/locallang.xlf:label-name" />**</label></b><br />

**Comment by angeloprevitali** [comment]
This isn't a TypoScript problem.

**Comment by kartolo** [comment]
it's not using fluid engine. Then it's not possible.

**Comment by angeloprevitali** [comment]
I know: but on the direct_mail i can add something like this in the template and it works:
`<tr>
              <td><table border="0" cellpadding="0" cellspacing="0" style="width:100%">
                  <tr>
                    <td align="left" valign="top" class="inhalte"><p class="webview">###USER_name### </p>
                      <f:format.raw>{inhalte}</f:format.raw></td>
                  </tr>
                  <tr>`

**Comment by angeloprevitali** [comment]
Any plans about rewriting the direct_mail and/or the direct_mail_subscription on FLUID?

**Comment by joneppie** [comment]
What's missing to merge?

**Comment by mz-aimcom** [comment]
@kartolo Hi,
I had a new error after activating the package `helhum/typo3-secure-web`. To make the subscription work, I had to rename the file `fe_adminLib.php` to `user_feAdmin.php` (to match the name of the class).

**Pull request merged**
